In [1]:
import numpy as np

# Subway ridership for 5 stations on 10 different days
ridership = np.array([
    [   0,    0,    2,    5,    0],
    [1478, 3877, 3674, 2328, 2539],
    [1613, 4088, 3991, 6461, 2691],
    [1560, 3392, 3826, 4787, 2613],
    [1608, 4802, 3932, 4477, 2705],
    [1576, 3933, 3909, 4979, 2685],
    [  95,  229,  255,  496,  201],
    [   2,    0,    1,   27,    0],
    [1438, 3785, 3589, 4174, 2215],
    [1342, 4043, 4009, 4665, 3033]
])


In [3]:
# Accessing elements
print ridership[1, 3]
print ridership[1:3, 3:5]
print ridership[1, :]

2328
[[2328 2539]
 [6461 2691]]
[1478 3877 3674 2328 2539]


In [8]:
# Vectorized operations on rows or columns
print ridership[0, :]
print ridership[1, :]
print ridership[0, :] + ridership[1, :]
print ridership[:, 0] + ridership[:, 1]
print ridership[:, 0] 
print ridership[:, 1]

[0 0 2 5 0]
[1478 3877 3674 2328 2539]
[1478 3877 3676 2333 2539]
[   0 5355 5701 4952 6410 5509  324    2 5223 5385]
[   0 1478 1613 1560 1608 1576   95    2 1438 1342]
[   0 3877 4088 3392 4802 3933  229    0 3785 4043]


In [9]:
# Vectorized operations on entire arrays

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
print a
print b
print a + b

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [33]:
## First find the station with the maximun riders on the first day
print ridership[0,:].max() # max value for the riders
print ridership[0,:].argmax() # station with the max value for riders
max_station = ridership[0,:].argmax()

# Find the mean riders per day for that station
print ridership[:,max_station]
mean_for_max = ridership[:,max_station].mean()
# Now find the mean ridership overall for comparasion 
print  ridership.mean()


5
3
[   5 2328 6461 4787 4477 4979  496   27 4174 4665]
2342.6


In [34]:
def mean_riders_for_max_station(ridership):
    ## First find the station with the maximun riders on the first day
    max_station = ridership[0,:].argmax()
    # Find the mean riders per day for that station
    mean_for_max = ridership[:,max_station].mean()
    # Now find the mean ridership overall for comparasion 
    overall_mean = ridership.mean()
    
    return (overall_mean,mean_for_max)


In [35]:
mean_riders_for_max_station(ridership)

(2342.5999999999999, 3239.9000000000001)