In [13]:
import pandas as pd
import numpy as np

In [14]:
daily_engagement = pd.read_csv('daily_engagement_full.csv')

In [15]:
len(daily_engagement['acct'].unique())

1237

In [16]:
def standardize_data(values):
    standardized_values = (values - value.mean()) / values.std()
    return standardized_values

In [17]:
a = np.array([1,2,3,4,5])
b = np.array([True,True,False,False,False])

In [18]:
a[a>2]

array([3, 4, 5])

In [21]:
## using index arrays
a = np.array([1, 2, 3, 4])
b = np.array([True, True, False, False])
    
print a[b]
print a[np.array([True, False, True, False])]

[1 2]
[1 3]


In [25]:
# Creating the index array using vectorized operations

a = np.array([1, 2, 3, 2, 1])
b = (a >= 2)
    
print a[b]
print a[a >= 2]
print b

[2 3 2]
[2 3 2]
[False  True  True  True False]


In [26]:
# Creating the index array using vectorized operations on another array
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 2, 3, 2, 1])
    
print b == 2
print a[b == 2]

[False  True False  True False]
[2 4]
