In [1]:
import tensorflow as tf
import numpy as np
import math

sess = tf.InteractiveSession()

In [2]:
# Some simple constants
x1 = tf.Variable(tf.truncated_normal([5],
                 mean=3, stddev=1./math.sqrt(5)))
x2 = tf.Variable(tf.truncated_normal([5],
                 mean=-1, stddev=1./math.sqrt(5)))
x3 = tf.Variable(tf.truncated_normal([5],
                 mean=0, stddev=1./math.sqrt(5)))

In [4]:
sess.run(tf.initialize_all_variables())

Instructions for updating:
Use `tf.global_variables_initializer` instead.


In [5]:
# Squaring makes large values extreme (but positive)
# Be careful if you have negative values
sqx2 = x2 * x2
print(x2.eval())
print(sqx2.eval())

[-1.12935555 -1.447106   -0.9717055  -0.92253685 -0.68734276]
[ 1.27544391  2.09411573  0.94421154  0.85107422  0.47244006]


In [6]:
# Logarithm makes small values more pronounced (and negative)
# Be careful that your algorithm can handle negative numbers
logx1 = tf.log(x1)
print(x1.eval())
print(logx1.eval())

[ 3.37055492  3.50794649  2.58961797  2.86594558  2.9070797 ]
[ 1.2150774   1.25503087  0.95151037  1.05289841  1.06714904]


In [7]:
# "sigmoid" is a common transformation in deep learning
# Extreme values get flattened to +1 or 0
# Inputs closer to zero stay similar, sigmoid(0) = 0.5
sigx3 = tf.sigmoid(x3)
print(x3.eval())
print(sigx3.eval())

[-0.35314384 -0.82414603  0.34600779  0.27871811  0.47546735]
[ 0.41262028  0.30488428  0.58564919  0.56923193  0.61667699]


In [8]:
# We linearly combine multiple inputs, then transform
w1 = tf.constant(0.1)
w2 = tf.constant(0.2)
sess.run(tf.initialize_all_variables())
n1 = tf.sigmoid(w1*x1 + w2*x2)
print((w1*x1).eval())
print((w2*x2).eval())
print(n1.eval())

Instructions for updating:
Use `tf.global_variables_initializer` instead.
[ 0.2914916   0.26341268  0.32066321  0.2833378   0.33312762]
[-0.09921171 -0.18381618 -0.30847168 -0.25243002 -0.07581579]
[ 0.54792243  0.51988864  0.50304788  0.50772637  0.56397539]
